# ==============================================================================
# INSTRUMENTAL-VARIABLE ANALYSIS SCRIPT
# ==============================================================================
#
# Author: Khaled Aboul Azm
#
# Script:
#   02_IV_inequalities.R
#
# Purpose:
# This script performs the instrumental-variable analyses for the thesis,
# including the one-sample Mendelian randomization analyses, assessment of
# instrument validity, and partial-identification analyses. It also generates
# the corresponding tables and figures.
#
# ==============================================================================
# ANALYSIS WORKFLOW
# ==============================================================================
#
# The thesis analyses are organized into the following scripts:
#
# 1. 01_descriptives_w_initial_analysis.R
#    Produces the descriptive statistics and performs the initial analyses.
#
# 2. 02_IV_inequalities.R
#    Evaluates the different discretisation methods, runs the IV inequalities,
#    and examines sparsity.
#
# The cleaned analysis dataset used here was generated by the preceding data
# management workflow and is loaded directly from:
#
#   data/vit.rda
#
# This script does not automatically source
# 01_descriptives_w_initial_analysis.R. The two scripts should normally be run
# in numerical order, but this script can be run independently provided that
# all required input datasets are available.
#
#
#
# Notes:
# This script was created by consolidating the analyses originally contained
# in the thesis notebooks. Plots and tables are primarily generated for
# inspection during the analysis. Objects needed by subsequent scripts may
# still be saved explicitly where required.
#
# ==============================================================================


# 1. INITIAL SETUP -------------------------------------------------------------

# Remove objects left over from previous R sessions
rm(list = ls())

# Set general R options
options(
  stringsAsFactors = FALSE,
  scipen = 999,
  digits = 4
)

# Set a seed for reproducible procedures involving random processes
set.seed(12345)


# 2. REQUIRED PACKAGES ---------------------------------------------------------

# Packages included in tidyverse, such as dplyr, tidyr, ggplot2, tibble, and
# purrr, do not need to be loaded separately.
required_packages <- c(
  "tidyverse",
  "lme4",
  "lmerTest",
  "hrbrthemes",
  "ExclusionTable",
  "viridis",
  "gt",
  "AER",
  "sandwich",
  "gtsummary",
  "ggdag",
  "knitr",
  "scales"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "The following required packages are not installed: ",
      paste(missing_packages, collapse = ", "),
      "."
    ),
    call. = FALSE
  )
}

invisible(
  lapply(
    required_packages,
    library,
    character.only = TRUE
  )
)


# 3. PROJECT DIRECTORIES -------------------------------------------------------

# The project location can be changed through the IIVITD_PROJECT_DIR
# environment variable. The GenEpi/BISON project location is used by default.
project_dir <- Sys.getenv(
  "IIVITD_PROJECT_DIR",
  unset = path.expand("~/ii2025MRVitD")
)

analysis_dir <- file.path(project_dir, "analysis")
data_dir <- file.path(project_dir, "data")
results_dir <- file.path(project_dir, "results")

tables_dir <- file.path(results_dir, "tables")
figures_dir <- file.path(results_dir, "figures")
models_dir <- file.path(results_dir, "models")


# 4. INPUT FILES ---------------------------------------------------------------

# Main cleaned analysis dataset
vit_data_file <- file.path(data_dir, "vit.rda")



# 5. DIRECTORY AND FILE CHECKS -------------------------------------------------

required_directories <- c(
  project_dir,
  analysis_dir,
  data_dir
)

missing_directories <- required_directories[
  !dir.exists(required_directories)
]

if (length(missing_directories) > 0) {
  stop(
    paste0(
      "The following required directories were not found:\n",
      paste0(" - ", missing_directories, collapse = "\n"),
      "\nCheck the project location or set IIVITD_PROJECT_DIR."
    ),
    call. = FALSE
  )
}

# Create output directories if necessary
output_directories <- c(
  results_dir,
  tables_dir,
  figures_dir,
  models_dir
)

invisible(
  lapply(
    output_directories,
    dir.create,
    recursive = TRUE,
    showWarnings = FALSE
  )
)

required_input_files <- c(
  vit_data_file,
  gwas_results
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste0(
      "The following required input files were not found:\n",
      paste0(" - ", missing_input_files, collapse = "\n"),
      "\nCheck the file locations or set the relevant environment variables."
    ),
    call. = FALSE
  )
}


# 6. LOAD ANALYSIS DATA --------------------------------------------------------

# Record the names of the objects loaded from the RData file.
loaded_vit_objects <- load(vit_data_file)

message(
  "Loaded objects from ", vit_data_file, ": ",
  paste(loaded_vit_objects, collapse = ", ")
)


# 7. SETUP SUMMARY -------------------------------------------------------------

message("Project directory: ", project_dir)
message("Analysis directory: ", analysis_dir)
message("Data directory: ", data_dir)
message("Results directory: ", results_dir)
message("GWAS results file: ", gwas_results)




###################################################################################



######################
# Discretization
######################


vit_disc <- vit %>%
  mutate(
    ## -------------------------
    ## Vitamin D discretisations
    ## -------------------------
    
    ## ESPGHAN
    vitd_espghan = case_when(
      vitd25_nmol < 25 ~ 0L,
      vitd25_nmol < 50 ~ 1L,
      vitd25_nmol >= 50 ~ 2L,
      TRUE ~ NA_integer_
    ),
    
    ## IOM
    vitd_iom = case_when(
      vitd25_nmol < 30 ~ 0L,
      vitd25_nmol < 50 ~ 1L,
      vitd25_nmol >= 50 ~ 2L,
      TRUE ~ NA_integer_
    ),
    
    ## IDEFICS
    vitd_idefics = case_when(
      vitd25_nmol < 50 ~ 0L,
      vitd25_nmol < 75 ~ 1L,
      vitd25_nmol >= 75 ~ 2L,
      TRUE ~ NA_integer_
    ),
    
    ## Binary
    vitd_binary50 = if_else(vitd25_nmol < 50, 0L, 1L, missing = NA_integer_),
    
    ## Empirical partitions
    vitd_quintile = ntile(vitd25_nmol, 5) - 1L,
    vitd_decile   = ntile(vitd25_nmol, 10) - 1L,
    
    ## -------------------------
    ## z_mets discretisations
    ## -------------------------
    
    ## Equal-width ("Borel") partitions
    zmets_borel3 = cut(
      z_mets,
      breaks = seq(min(z_mets, na.rm = TRUE),
                   max(z_mets, na.rm = TRUE),
                   length.out = 4),
      include.lowest = TRUE,
      labels = FALSE
    ) - 1L,
    
    zmets_borel5 = cut(
      z_mets,
      breaks = seq(min(z_mets, na.rm = TRUE),
                   max(z_mets, na.rm = TRUE),
                   length.out = 6),
      include.lowest = TRUE,
      labels = FALSE
    ) - 1L,
    
    zmets_borel10 = cut(
      z_mets,
      breaks = seq(min(z_mets, na.rm = TRUE),
                   max(z_mets, na.rm = TRUE),
                   length.out = 11),
      include.lowest = TRUE,
      labels = FALSE
    ) - 1L,
    
    ## Equal-probability ("CDF") partitions
    zmets_cdf3 = ntile(z_mets, 3) - 1L,
    zmets_cdf5 = ntile(z_mets, 5) - 1L,
    zmets_cdf10 = ntile(z_mets, 10) - 1L,
    
    ## Binary partitions (Added)
    zmets_binary0 = if_else(z_mets >= 0, 1L, 0L, missing = NA_integer_),
    zmets_binary_median = if_else(z_mets >= median(z_mets, na.rm = TRUE), 1L, 0L, missing = NA_integer_)
  )

snp_vars_thesis <- c("rs11732044_t","rs116970203_a")

vit_disc_thesis <- vit_disc %>%
  mutate(
    snp_combination = apply(
      select(., all_of(snp_vars_thesis)),
      1,
      function(x) {
        if (any(is.na(x))) NA_character_
        else paste0(x, collapse = "")
      }
    ),
    
    snp_additive = rowSums(
      select(., all_of(snp_vars_thesis)),
      na.rm = FALSE
    )
  )


#Coded as:
  
#  | Variable | 0                 | 1             | 2           |
#  |----------|-------------------|---------------|-------------|
#  | ESPGHAN  | Severe deficiency | Insufficiency | Sufficiency |
#  | IOM      | Deficient         | Inadequate    | Sufficient  |
#  | IDEFICS  | Deficient         | Insufficient  | Sufficient  |


# ===========================================================
# Visualising the effects of discretization
# ===========================================================

# Visualising Exposure Discretization

plot_discretization_heatmap <- function(
    summary_tbl,
    outcome_var,
    exposure_seq,
    joint_type = "combination",
    reference_exposure = NULL,
    relative = FALSE
) {
  
  joint_instrument <- if (joint_type == "combination") {
    "snp_combination"
  } else {
    "snp_additive"
  }
  
  # ---------------------------------------------------------
  # 1. Select relevant instruments
  # ---------------------------------------------------------
  
  instrument_order <- c(
    "rs11732044_t",
    "rs116970203_a",
    joint_instrument
  )
  
  instrument_labels <- c(
    "rs11732044_t" = "SNP 1",
    "rs116970203_a" = "SNP 2",
    "snp_combination" = "Joint",
    "snp_additive" = "Joint"
  )
  
  # ---------------------------------------------------------
  # 2. Extract data
  # ---------------------------------------------------------
  
  plot_data <- summary_tbl %>%
    filter(
      outcome == outcome_var,
      exposure %in% exposure_seq,
      instrument %in% instrument_order
    ) %>%
    mutate(
      exposure = factor(exposure, levels = exposure_seq),
      instrument = factor(
        instrument,
        levels = instrument_order
      ),
      instrument_label = case_when(
        as.character(instrument) == "rs11732044_t" ~ "SNP 1",
        as.character(instrument) == "rs116970203_a" ~ "SNP 2",
        as.character(instrument) %in% c(
          "snp_combination",
          "snp_additive"
        ) ~ "Joint",
        TRUE ~ as.character(instrument)
      )
    ) %>%
    select(
      exposure,
      x_levels,
      instrument,
      instrument_label,
      max_value
    ) %>%
    distinct()
  
  # ---------------------------------------------------------
  # 3. Calculate values
  # ---------------------------------------------------------
  
  if (relative) {
    
    if (is.null(reference_exposure)) {
      reference_exposure <- exposure_seq[1]
    }
    
    reference_values <- plot_data %>%
      filter(exposure == reference_exposure) %>%
      select(
        instrument,
        reference_value = max_value
      )
    
    plot_data <- plot_data %>%
      left_join(
        reference_values,
        by = "instrument"
      ) %>%
      mutate(
        value = max_value - reference_value
      )
    
  } else {
    
    plot_data <- plot_data %>%
      mutate(value = max_value)
  }
  
  # ---------------------------------------------------------
  # 4. Exposure labels
  # ---------------------------------------------------------
  
  exposure_labels <- plot_data %>%
    distinct(exposure, x_levels) %>%
    mutate(
      label = paste0(
        as.character(exposure),
        "\n(",
        x_levels,
        " categories)"
      )
    )
  
  x_labels <- exposure_labels$label
  names(x_labels) <- exposure_labels$exposure
  
  # ---------------------------------------------------------
  # 5. Absolute heatmap
  # ---------------------------------------------------------
  
  if (!relative) {
    
    # Maximum value in the actual data
    data_max <- max(plot_data$value, na.rm = TRUE)
    
    # Keep the upper limit at least 1, but allow values > 1
    scale_max <- max(1, data_max)
    
    p <- ggplot(
      plot_data,
      aes(
        x = exposure,
        y = instrument_label,
        fill = value
      )
    ) +
      
      geom_tile(
        colour = "white",
        linewidth = 0.8
      ) +
      
      # Values >= 1 are red; values < 1 are white
      geom_text(
        aes(
          label = sprintf("%.2f", value),
          colour = value >= 1
        ),
        size = 3.5,
        fontface = "bold"
      ) +
      
      scale_colour_manual(
        values = c(
          "FALSE" = "white",
          "TRUE" = "red"
        ),
        guide = "none"
      ) +
      
      # Light = low inequality
      # Dark = high inequality
      scale_fill_gradient(
        low = "grey95",
        high = "grey25",
        limits = c(0, scale_max),
        breaks = pretty(c(0, scale_max)),
        name = "Maximum\ninequality"
      ) +
      
      labs(
        x = NULL,
        y = NULL,
        title = paste0(
          outcome_var,
          " — ",
          joint_type,
          " instrument"
        )
      )
    
  } else {
    
    # -------------------------------------------------------
    # Relative / sensitivity heatmap
    # -------------------------------------------------------
    
    max_abs <- max(abs(plot_data$value), na.rm = TRUE)
    
    p <- ggplot(
      plot_data,
      aes(
        x = exposure,
        y = instrument_label,
        fill = value
      )
    ) +
      
      geom_tile(
        colour = "white",
        linewidth = 0.8
      ) +
      
      geom_text(
        aes(
          label = sprintf("%.2f", value),
          colour = value > 0
        ),
        size = 3.5,
        fontface = "bold"
      ) +
      
      scale_colour_manual(
        values = c(
          "FALSE" = "white",
          "TRUE" = "red"
        ),
        guide = "none"
      ) +
      
      scale_fill_gradient2(
        low = "grey80",
        mid = "white",
        high = "grey25",
        midpoint = 0,
        limits = c(-max_abs, max_abs),
        name = "Change in\nmax inequality"
      ) +
      
      labs(
        x = NULL,
        y = NULL,
        title = paste0(
          outcome_var,
          " — ",
          joint_type,
          " instrument"
        ),
        subtitle = "Change relative to reference discretisation"
      )
  }
  
  # ---------------------------------------------------------
  # 6. Final formatting
  # ---------------------------------------------------------
  
  p +
    scale_x_discrete(
      labels = x_labels
    ) +
    
    theme_minimal(base_size = 11) +
    
    theme(
      panel.grid = element_blank(),
      
      axis.text.x = element_text(
        angle = 0,
        hjust = 0.5
      ),
      
      axis.text.y = element_text(
        face = "bold"
      ),
      
      plot.title = element_text(
        face = "bold"
      ),
      
      plot.subtitle = element_text(
        size = 9
      ),
      
      legend.position = "right"
    )
}

vitd_labels <- c(
  vitd_espghan  = "ESPGHAN",
  vitd_iom      = "IOM",
  vitd_idefics  = "IDEFICS",
  vitd_binary50 = "Binary",
  vitd_quintile = "Quintiles",
  vitd_decile   = "Deciles"
)

plot_discretization_heatmap(
  summary_tbl = summary_tbl2,
  outcome_var = "zmets_binary_median",
  exposure_seq = vitd_vars,
  joint_type = "combination",
  relative = FALSE
)

plot_discretization_heatmap(
  summary_tbl = summary_tbl2,
  outcome_var = "zmets_borel10",
  exposure_seq = vitd_vars,
  joint_type = "additive",
  relative = FALSE
)


plot_outcome_discretization_heatmap <- function(
    summary_tbl,
    exposure_var,
    outcome_seq,
    joint_type = "combination"
) {
  
  joint_instrument <- if (joint_type == "combination") {
    "snp_combination"
  } else {
    "snp_additive"
  }
  
  # ---------------------------------------------------------
  # 1. Select relevant instruments
  # ---------------------------------------------------------
  
  instrument_order <- c(
    "rs11732044_t",
    "rs116970203_a",
    joint_instrument
  )
  
  instrument_labels <- c(
    "rs11732044_t" = "SNP 1",
    "rs116970203_a" = "SNP 2",
    "snp_combination" = "Joint",
    "snp_additive" = "Joint"
  )
  
  # ---------------------------------------------------------
  # 2. Extract data
  # ---------------------------------------------------------
  
  plot_data <- summary_tbl %>%
    filter(
      exposure == exposure_var,
      outcome %in% outcome_seq,
      instrument %in% instrument_order
    ) %>%
    mutate(
      outcome = factor(
        outcome,
        levels = outcome_seq
      ),
      instrument = factor(
        instrument,
        levels = instrument_order
      ),
      instrument_label = case_when(
        as.character(instrument) == "rs11732044_t" ~ "SNP 1",
        as.character(instrument) == "rs116970203_a" ~ "SNP 2",
        as.character(instrument) %in% c(
          "snp_combination",
          "snp_additive"
        ) ~ "Joint",
        TRUE ~ as.character(instrument)
      )
    ) %>%
    select(
      outcome,
      y_levels,
      instrument,
      instrument_label,
      max_value
    ) %>%
    distinct()
  
  # ---------------------------------------------------------
  # 3. Outcome labels
  # ---------------------------------------------------------
  
  outcome_labels <- plot_data %>%
    distinct(outcome, y_levels) %>%
    mutate(
      label = paste0(
        as.character(outcome),
        "\n(",
        y_levels,
        " categories)"
      )
    )
  
  x_labels <- outcome_labels$label
  names(x_labels) <- outcome_labels$outcome
  
  # ---------------------------------------------------------
  # 4. Determine colour scale
  # ---------------------------------------------------------
  
  data_max <- max(
    plot_data$max_value,
    na.rm = TRUE
  )
  
  scale_max <- max(
    1,
    data_max
  )
  
  # ---------------------------------------------------------
  # 5. Heatmap
  # ---------------------------------------------------------
  
  p <- ggplot(
    plot_data,
    aes(
      x = outcome,
      y = instrument_label,
      fill = max_value
    )
  ) +
    
    geom_tile(
      colour = "white",
      linewidth = 0.8
    ) +
    
    # White text normally; red when inequality >= 1
    geom_text(
      aes(
        label = sprintf("%.2f", max_value),
        colour = max_value >= 1
      ),
      size = 3.5,
      fontface = "bold"
    ) +
    
    scale_colour_manual(
      values = c(
        "FALSE" = "white",
        "TRUE" = "red"
      ),
      guide = "none"
    ) +
    
    # Darker = larger inequality
    scale_fill_gradient(
      low = "grey95",
      high = "grey25",
      limits = c(0, scale_max),
      name = "Maximum\ninequality"
    ) +
    
    scale_x_discrete(
      labels = x_labels
    ) +
    
    labs(
      x = NULL,
      y = NULL,
      title = paste0(
        exposure_var,
        " → outcome discretisation"
      ),
      subtitle = paste0(
        "Fixed exposure; ",
        joint_type,
        " instrument"
      )
    ) +
    
    theme_minimal(base_size = 11) +
    
    theme(
      panel.grid = element_blank(),
      
      axis.text.x = element_text(
        angle = 0,
        hjust = 0.5
      ),
      
      axis.text.y = element_text(
        face = "bold"
      ),
      
      plot.title = element_text(
        face = "bold"
      ),
      
      plot.subtitle = element_text(
        size = 9
      ),
      
      legend.position = "right"
    )
  
  return(p)
}


###########################################
# Instrumental Variable Inequalities
# The code is an adapted version from Elizabeth Diemer's work.
##########################################

run_instrumental_inequalities_singlejointiv <- function(data, y, x, instrument, covariate = NULL) {
  
  # 1. Build the base dataframe
  dat <- data.frame(
    Y  = factor(data[[y]]),
    X  = factor(data[[x]]),
    IV = factor(data[[instrument]])
  )
  
  # 2. Path A: With a Covariate (Stratified)
  if (!is.null(covariate)) {
    dat$C <- factor(data[[covariate]])
    
    # Calculate counts across 4 dimensions: IV, X, Y, Covariate
    cnt_xyzc <- xtabs(~ IV + X + Y + C, data = dat)
    
    # prop.table with margin c(1,4) calculates P(X, Y | IV, C)
    p_xyzc <- prop.table(cnt_xyzc, margin = c(1, 4))
    p_xyzc[!is.finite(p_xyzc)] <- NA_real_
    
    x_levels <- dimnames(p_xyzc)$X
    c_levels <- dimnames(p_xyzc)$C
    
    # Create a grid of all X levels and Covariate levels to iterate through
    xc_grid <- expand.grid(X = seq_along(x_levels), C = seq_along(c_levels))
    
    res <- lapply(seq_len(nrow(xc_grid)), function(r) {
      ix <- xc_grid$X[r]
      ic <- xc_grid$C[r]
      
      mat <- p_xyzc[, ix, , ic]   # Z × Y matrix for this specific X and C level
      
      max_per_y <- apply(mat, 2, function(col) {
        if (all(is.na(col))) 0 else max(col, na.rm = TRUE)
      })
      
      ineq_val <- sum(max_per_y, na.rm = TRUE)
      
      data.frame(
        X = x_levels[ix],
        Covariate_Level = c_levels[ic],
        inequality_value = ineq_val,
        violated = ineq_val > (1 + 1e-8)
      )
    })
    
    # 3. Path B: Without a Covariate (Your Original Logic)
  } else {
    cnt_xyz <- xtabs(~ IV + X + Y, data = dat)
    
    # prop.table with margin 1 calculates P(X, Y | IV)
    p_xyz <- prop.table(cnt_xyz, margin = 1)
    p_xyz[!is.finite(p_xyz)] <- NA_real_
    
    x_levels <- dimnames(p_xyz)$X
    
    res <- lapply(seq_along(x_levels), function(ix) {
      mat <- p_xyz[, ix, ]   # Z × Y matrix
      
      max_per_y <- apply(mat, 2, function(col) {
        if (all(is.na(col))) 0 else max(col, na.rm = TRUE)
      })
      
      ineq_val <- sum(max_per_y, na.rm = TRUE)
      
      data.frame(
        X = x_levels[ix],
        Covariate_Level = NA, # Pad with NA so both paths return the same structure
        inequality_value = ineq_val,
        violated = ineq_val > (1 + 1e-8)
      )
    })
  }
  
  res <- do.call(rbind, res)
  
  list(
    inequalities = res,
    max_value = max(res$inequality_value, na.rm = TRUE),
    violated = any(res$violated, na.rm = TRUE)
  )
}
# ===========================================================
## Calculating the inequalities for the unadjusted setting
# ===========================================================
vitd_vars <- c(
  "vitd_espghan",
  "vitd_iom",
  "vitd_idefics",
  "vitd_binary50",
  "vitd_quintile",
  "vitd_decile"
)

y_vars <- c(
  "zmets_borel3",
  "zmets_borel5",
  "zmets_borel10",
  "zmets_cdf3",
  "zmets_cdf5",
  "zmets_cdf10",
  "zmets_binary_median",
  "zmets_binary0"
)

instrument_vars <- c(
  "rs11732044_t",
  "rs116970203_a",          
  "snp_combination",
  "snp_additive"
)

results_raw <- list()
summary_raw <- list()

k <- 1

for (instrument in instrument_vars) {
  for (yvar in y_vars) {
    for (xvar in vitd_vars) {
      
      # ---------------------------------------------------------
      # Run instrumental inequalities
      # ---------------------------------------------------------
      ineq <- run_instrumental_inequalities_singlejointiv(
        data = vit_disc_thesis,
        y = yvar,
        x = xvar,
        instrument = instrument
      )
      
      # ---------------------------------------------------------
      # Complete-case data for this exact G, X, Y specification
      # ---------------------------------------------------------
      cell_data <- vit_disc_thesis %>%
        dplyr::transmute(
          z = .data[[instrument]],
          x = .data[[xvar]],
          y = .data[[yvar]]
        ) %>%
        tidyr::drop_na()
      
      # Observed category levels in the complete-case data
      z_vals <- unique(cell_data$z)
      x_vals <- unique(cell_data$x)
      y_vals <- unique(cell_data$y)
      
      # ---------------------------------------------------------
      # Observed counts n_zxy
      # ---------------------------------------------------------
      observed_cells <- cell_data %>%
        dplyr::count(z, x, y, name = "cell_n")
      
      # ---------------------------------------------------------
      # Create all X x Y cells within every Z = z contingency table.
      #
      # table_n         = N_z
      # relative_cell_n = n_zxy / N_z
      # ---------------------------------------------------------
      all_cells <- tidyr::expand_grid(
        z = z_vals,
        x = x_vals,
        y = y_vals
      ) %>%
        dplyr::left_join(
          observed_cells,
          by = c("z", "x", "y")
        ) %>%
        dplyr::mutate(
          cell_n = tidyr::replace_na(cell_n, 0L),
          empty_cell = cell_n == 0L,
          singleton_cell = cell_n == 1L
        ) %>%
        dplyr::group_by(z) %>%
        dplyr::mutate(
          # Total N within this instrument-level contingency table
          table_n = sum(cell_n),
          
          # n_zxy / N_z:
          # empirical P(X = x, Y = y | Z = z)
          relative_cell_n = dplyr::if_else(
            table_n > 0,
            cell_n / table_n,
            NA_real_
          )
        ) %>%
        dplyr::ungroup()
      
      # ---------------------------------------------------------
      # One-row summary for each instrument level / Z table
      # ---------------------------------------------------------
      z_table_summary <- all_cells %>%
        dplyr::group_by(z) %>%
        dplyr::summarise(
          table_n = dplyr::first(table_n),
          
          # Number of possible cells in this X x Y table
          possible_xy_cells = dplyr::n(),
          
          # Empty and non-empty X x Y cells in this Z table
          nonempty_xy_cells = sum(cell_n > 0L),
          empty_xy_cells = sum(cell_n == 0L),
          pct_empty_xy_cells = 100 * mean(cell_n == 0L),
          
          # Very small cells
          singleton_xy_cells = sum(cell_n == 1L),
          
          # Distribution of cell n, including zeros
          min_cell_n = min(cell_n),
          median_cell_n = median(cell_n),
          mean_cell_n = mean(cell_n),
          
          # Distribution among populated cells only
          min_nonzero_cell_n = min(cell_n[cell_n > 0L]),
          median_nonzero_cell_n = median(cell_n[cell_n > 0L]),
          
          # Relative within-Z-table cell population: n_zxy / N_z
          min_nonzero_relative_cell_n = min(
            relative_cell_n[cell_n > 0L]
          ),
          median_nonzero_relative_cell_n = median(
            relative_cell_n[cell_n > 0L]
          ),
          max_relative_cell_n = max(relative_cell_n),
          
          .groups = "drop"
        )
      
      # ---------------------------------------------------------
      # Store full cell-level and table-level results
      # ---------------------------------------------------------
      spec_name <- paste(instrument, xvar, yvar, sep = "_")
      
      results_raw[[spec_name]] <- list(
        ineq = ineq,
        max_value = ineq$max_value,
        violated = ineq$violated,
        
        # One row per Z x X x Y cell
        cell_counts = all_cells,
        
        # One row per Z level / contingency table
        z_table_summary = z_table_summary
      )
      
      # ---------------------------------------------------------
      # One row per full instrument-exposure-outcome specification
      # ---------------------------------------------------------
      summary_raw[[k]] <- data.frame(
        instrument = instrument,
        exposure = xvar,
        outcome = yvar,
        
        instrument_levels = length(z_vals),
        x_levels = length(x_vals),
        y_levels = length(y_vals),
        
        max_value = ineq$max_value,
        violated = ineq$violated,
        
        # Overall N for this specification
        n_complete_cases = nrow(cell_data),
        
        # Number of separate Z-specific X x Y tables
        n_z_tables = dplyr::n_distinct(all_cells$z),
        
        # Each Z table has x_levels * y_levels possible cells
        possible_xy_cells_per_z_table = length(x_vals) * length(y_vals),
        
        # N_z values across instrument levels
        min_table_n = min(z_table_summary$table_n),
        median_table_n = median(z_table_summary$table_n),
        mean_table_n = mean(z_table_summary$table_n),
        max_table_n = max(z_table_summary$table_n),
        
        # Sparsity across Z-specific X x Y tables
        mean_pct_empty_xy_cells = mean(z_table_summary$pct_empty_xy_cells),
        median_pct_empty_xy_cells = median(z_table_summary$pct_empty_xy_cells),
        max_pct_empty_xy_cells = max(z_table_summary$pct_empty_xy_cells),
        
        # Number of singleton cells across all Z-specific tables
        total_singleton_xy_cells = sum(z_table_summary$singleton_xy_cells),
        
        # Smallest non-zero conditional cell probability, n_zxy / N_z
        min_nonzero_relative_cell_n = min(
          z_table_summary$min_nonzero_relative_cell_n
        ),
        
        # Median of the table-specific medians
        median_relative_cell_n = median(
          z_table_summary$median_nonzero_relative_cell_n
        ),
        
        stringsAsFactors = FALSE
      )
      
      k <- k + 1
    }
  }
}

summary_tbl2 <- dplyr::bind_rows(summary_raw)

# On average, increasing the number of levels of the vitamin D discretisation leads to a smaller max inequality value.

# ===========================================================
# Adjusting for country
# ===========================================================

results2 <- list()
summary_list2 <- list()

k <- 1

for (instrument in instrument_vars) {
  for (yvar in y_vars) {
    for (xvar in vitd_vars) {
      
      # ---------------------------------------------------------
      # Run instrumental inequalities
      # ---------------------------------------------------------
      ineq <- run_instrumental_inequalities_singlejointiv(
        data = vit_disc_thesis,
        y = yvar,
        x = xvar,
        instrument = instrument,
        covariate = "country"
      )
      
      # ---------------------------------------------------------
      # Complete-case data for this specific country, Z, X, Y analysis
      # ---------------------------------------------------------
      cell_data <- vit_disc_thesis %>%
        dplyr::transmute(
          country = .data[["country"]],
          z = .data[[instrument]],
          x = .data[[xvar]],
          y = .data[[yvar]]
        ) %>%
        tidyr::drop_na()
      
      # ---------------------------------------------------------
      # Observed levels in the exact complete-case dataset
      # ---------------------------------------------------------
      z_vals <- unique(cell_data$z)
      x_vals <- unique(cell_data$x)
      y_vals <- unique(cell_data$y)
      
      # Keep ONLY country × instrument-level combinations
      # that actually occur in the data.
      #
      # This avoids constructing artificial tables such as
      # country = BEL, z = 3 when no Belgian participant has z = 3.
      observed_country_z_tables <- cell_data %>%
        dplyr::distinct(country, z)
      
      # All possible X × Y cells
      possible_xy_cells <- tidyr::expand_grid(
        x = x_vals,
        y = y_vals
      )
      
      # ---------------------------------------------------------
      # Observed cell counts: n_country,z,x,y
      # ---------------------------------------------------------
      observed_cells <- cell_data %>%
        dplyr::count(country, z, x, y, name = "cell_n")
      
      # ---------------------------------------------------------
      # Create all X × Y cells within each OBSERVED country × Z table
      # ---------------------------------------------------------
      all_cells <- dplyr::cross_join(
        observed_country_z_tables,
        possible_xy_cells
      ) %>%
        dplyr::left_join(
          observed_cells,
          by = c("country", "z", "x", "y")
        ) %>%
        dplyr::mutate(
          cell_n = tidyr::replace_na(cell_n, 0L),
          empty_cell = cell_n == 0L,
          singleton_cell = cell_n == 1L
        ) %>%
        dplyr::group_by(country, z) %>%
        dplyr::mutate(
          # Total N in the specific country × Z contingency table:
          # N_country,z
          table_n = sum(cell_n),
          
          # n_country,z,x,y / N_country,z
          relative_cell_n = cell_n / table_n
        ) %>%
        dplyr::ungroup()
      
      # ---------------------------------------------------------
      # One row per observed country × instrument-level table
      # ---------------------------------------------------------
      z_table_summary <- all_cells %>%
        dplyr::group_by(country, z) %>%
        dplyr::summarise(
          # Table sample size: N_country,z
          table_n = dplyr::first(table_n),
          
          # Number of possible X × Y cells
          possible_xy_cells = dplyr::n(),
          
          # Number / percentage of empty cells
          nonempty_xy_cells = sum(cell_n > 0L),
          empty_xy_cells = sum(cell_n == 0L),
          pct_empty_xy_cells = 100 * mean(cell_n == 0L),
          
          # Number of cells containing only one participant
          singleton_xy_cells = sum(cell_n == 1L),
          
          # Relative cell population:
          # n_country,z,x,y / N_country,z
          min_nonzero_relative_cell_n = min(relative_cell_n[cell_n > 0L]),
          median_nonzero_relative_cell_n = median(relative_cell_n[cell_n > 0L]),
          max_relative_cell_n = max(relative_cell_n),
          
          .groups = "drop"
        )
      
      # ---------------------------------------------------------
      # Store full cell-level and table-level results
      # ---------------------------------------------------------
      spec_name <- paste(instrument, xvar, yvar, sep = "_")
      
      results2[[spec_name]] <- list(
        ineq = ineq,
        max_value = ineq$max_value,
        violated = ineq$violated,
        
        # One row per Z x X x Y cell
        cell_counts = all_cells,
        
        # One row per Z level / contingency table
        z_table_summary = z_table_summary
      )
      
      # ---------------------------------------------------------
      # One row per full instrument-exposure-outcome specification
      # ---------------------------------------------------------
      summary_list2[[k]] <- data.frame(
        instrument = instrument,
        exposure = xvar,
        outcome = yvar,
        
        instrument_levels = length(z_vals),
        x_levels = length(x_vals),
        y_levels = length(y_vals),
        
        max_value = ineq$max_value,
        violated = ineq$violated,
        
        # Overall N for this specification
        n_complete_cases = nrow(cell_data),
        
        # Number of separate Z-specific X x Y tables
        n_z_tables = dplyr::n_distinct(
          interaction(all_cells$country, all_cells$z, drop = TRUE)
        ),
        
        # Each Z table has x_levels * y_levels possible cells
        possible_xy_cells_per_z_table = length(x_vals) * length(y_vals),
        
        # N_z values across instrument levels
        min_table_n = min(z_table_summary$table_n),
        median_table_n = median(z_table_summary$table_n),
        mean_table_n = mean(z_table_summary$table_n),
        max_table_n = max(z_table_summary$table_n),
        
        # Sparsity across Z-specific X x Y tables
        mean_pct_empty_xy_cells = mean(z_table_summary$pct_empty_xy_cells),
        median_pct_empty_xy_cells = median(z_table_summary$pct_empty_xy_cells),
        max_pct_empty_xy_cells = max(z_table_summary$pct_empty_xy_cells),
        
        # Number of singleton cells across all Z-specific tables
        total_singleton_xy_cells = sum(z_table_summary$singleton_xy_cells),
        
        # Smallest non-zero conditional cell probability, n_zxy / N_z
        min_nonzero_relative_cell_n = min(
          z_table_summary$min_nonzero_relative_cell_n
        ),
        
        # Median of the table-specific medians
        median_relative_cell_n = median(
          z_table_summary$median_nonzero_relative_cell_n
        ),
        
        stringsAsFactors = FALSE
      )
      
      k <- k + 1
    }
  }
}

summary_tbl2_C <- dplyr::bind_rows(summary_list2)


# ===========================================================
# We also considering adjusting for the country with the biggest sample.
# ===========================================================

# 1. Isolate the data for your chosen country
test_country <- "HUN" 
single_country_data <- subset(vit_disc_thesis, country == test_country)

detailed_list_single <- list() # To hold the detailed row-by-row inequalities
summary_list_single <- list()  # To hold the summary metrics
k <- 1

# 2. Run the loop on the single country dataset
for (instrument in instrument_vars) {
  for (yvar in y_vars) {
    for (xvar in vitd_vars) {
      
      # Run the test
      ineq <- run_instrumental_inequalities_singlejointiv(
        data = single_country_data, 
        y = yvar,
        x = xvar,
        instrument = instrument
      )
      
      # Extract detailed inequalities df and tag with current variables
      detailed_df <- ineq$inequalities
      detailed_df$country <- test_country
      detailed_df$instrument <- instrument
      detailed_df$exposure <- xvar
      detailed_df$outcome <- yvar
      
      # Store in our detailed list
      detailed_list_single[[k]] <- detailed_df
      
      # Store the summary metrics
      summary_list_single[[k]] <- data.frame(
        country = test_country,
        instrument = instrument,
        exposure = xvar,
        outcome = yvar,
        instrument_levels = dplyr::n_distinct(single_country_data[[instrument]], na.rm = TRUE),
        x_levels = dplyr::n_distinct(single_country_data[[xvar]], na.rm = TRUE),
        y_levels = dplyr::n_distinct(single_country_data[[yvar]], na.rm = TRUE),
        max_value = ineq$max_value,
        violated = ineq$violated
      )
      
      k <- k + 1
    }
  }
}

# Bind lists into single, flat data frames
detailed_tbl_single <- dplyr::bind_rows(detailed_list_single)
summary_tbl_single <- dplyr::bind_rows(summary_list_single)



# Inspection

# 1. Create a helper function for the repetitive styling
apply_gt_formatting <- function(data, is_grouped = FALSE) {
  
  if (is_grouped) {
    # Grouping logic
    tbl <- data %>%
      arrange(instrument, desc(max_value)) %>%
      group_by(instrument) %>%
      gt() %>%
      tab_options(
        row_group.background.color = "#f0f0f0",
        row_group.font.weight = "bold"
      )
  } else {
    # Standard logic
    tbl <- data %>% gt()
  }
  
  # Apply labels and colors to all tables
  tbl <- tbl %>%
    cols_label(
      exposure = "Exposure (Vit D)",
      outcome = "Outcome (MetS)",
      instrument_levels = "IV Levels",
      x_levels = "Exp. Levels",
      y_levels = "Out. Levels",
      max_value = "Max Value",
      violated = "Violated"
    ) %>%
    data_color(
      columns = violated,
      target_columns = everything(),
      fn = scales::col_factor(palette = c("white", "#ffe6e6"), domain = c(FALSE, TRUE))
    )
  
  # Add the instrument label back if it's not grouped
  if (!is_grouped) {
    tbl <- tbl %>% cols_label(instrument = "Instrument")
  }
  
  return(tbl)
}

# 2. Build the first set of tables
long_tbl           <- apply_gt_formatting(summary_tbl, is_grouped = FALSE)
grouped_long_tbl   <- apply_gt_formatting(summary_tbl, is_grouped = TRUE)
# grouped_long_tbl_c <- apply_gt_formatting(summary_tbl2_C, is_grouped = TRUE)

# 3. Build the second set of tables
long_tbl2           <- apply_gt_formatting(summary_tbl2, is_grouped = FALSE)
grouped_long_tbl2   <- apply_gt_formatting(summary_tbl2, is_grouped = TRUE)
grouped_long_tbl2_c <- apply_gt_formatting(summary_tbl2_C, is_grouped = TRUE)

# ===========================================================
# Visualising the results
# ===========================================================

# 1. Reshape the data for plotting
plot_data <- summary_tbl2 %>%
  tidyr::pivot_longer(
    cols = c(x_levels, y_levels, instrument_levels),
    names_to = "level_type",
    values_to = "number_of_levels"
  ) %>%
  dplyr::mutate(
    # Make the labels readable for the plot facets
    level_type = dplyr::case_when(
      level_type == "x_levels" ~ "Exposure Levels (Vitamin D)",
      level_type == "y_levels" ~ "Outcome Levels (Metabolic)",
      level_type == "instrument_levels" ~ "Instrument Levels (SNP)"
    )
  )

# 2. Generate the plot
ggplot(plot_data, aes(x = factor(number_of_levels), y = max_value)) +
  # Add boxplots to show the distribution spread
  geom_boxplot(outlier.shape = NA, fill = "gray90", color = "gray50") +
  # Overlay the actual data points, colored by whether they violated the bound
  geom_jitter(aes(color = violated), width = 0.2, alpha = 0.7, size = 2) +
  # Add the theoretical upper bound line
  geom_hline(yintercept = 1, linetype = "dashed", color = "red", linewidth = 1) +
  # Split the plot into three panels
  facet_wrap(~ level_type, scales = "free_x") +
  # Styling
  theme_minimal(base_size = 14) +
  scale_color_manual(values = c("FALSE" = "#2c7bb6", "TRUE" = "#d7191c")) +
  labs(
    title = "Effect of Variable Sparsity on Instrumental Inequalities",
    x = "Number of Categories (Levels)",
    y = "Maximum Inequality Value",
    color = "Violated Bound"
  ) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )

# 1. Reshape the data for plotting
plot_data <- summary_tbl2_C %>%
  tidyr::pivot_longer(
    cols = c(x_levels, y_levels, instrument_levels),
    names_to = "level_type",
    values_to = "number_of_levels"
  ) %>%
  dplyr::mutate(
    # Make the labels readable for the plot facets
    level_type = dplyr::case_when(
      level_type == "x_levels" ~ "Exposure Levels (Vitamin D)",
      level_type == "y_levels" ~ "Outcome Levels (Metabolic)",
      level_type == "instrument_levels" ~ "Instrument Levels (SNP)"
    )
  )

# 2. Generate the plot
ggplot(plot_data, aes(x = factor(number_of_levels), y = max_value)) +
  # Add boxplots to show the distribution spread
  geom_boxplot(outlier.shape = NA, fill = "gray90", color = "gray50") +
  # Overlay the actual data points, colored by whether they violated the bound
  geom_jitter(aes(color = violated), width = 0.2, alpha = 0.7, size = 2) +
  # Add the theoretical upper bound line
  geom_hline(yintercept = 1, linetype = "dashed", color = "red", linewidth = 1) +
  # Split the plot into three panels
  facet_wrap(~ level_type, scales = "free_x") +
  # Styling
  theme_minimal(base_size = 14) +
  scale_color_manual(values = c("FALSE" = "#2c7bb6", "TRUE" = "#d7191c")) +
  labs(
    title = "Effect of Variable Sparsity on Instrumental Inequalities",
    x = "Number of Categories (Levels)",
    y = "Maximum Inequality Value",
    color = "Violated Bound"
  ) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )



########################################
# Investingating Sparsity/Positivity violations
#######################################

sparsity_by_dimension <- summary_tbl2 %>%
  mutate(
    instrument = factor(instrument, levels = instrument_vars)
  ) %>%
  group_by(instrument, x_levels, y_levels) %>%
  summarise(
    # Sparsity
    mean_pct_empty_xy_cells = mean(mean_pct_empty_xy_cells),
    median_pct_empty_xy_cells = median(median_pct_empty_xy_cells),
    
    # Percentage of specifications in this tile that violate the inequalities
    pct_violated = 100 * mean(violated, na.rm = TRUE),
    
    # Number of specifications combined in the tile
    n_specifications = n(),
    
    # Other sparsity indicators
    mean_singleton_cells = mean(total_singleton_xy_cells),
    mean_min_table_n = mean(min_table_n),
    
    .groups = "drop"
  ) %>%
  mutate(
    x_levels = factor(
      x_levels,
      levels = sort(unique(x_levels)),
      labels = paste0(sort(unique(x_levels)), " levels")
    ),
    y_levels = factor(
      y_levels,
      levels = sort(unique(y_levels)),
      labels = paste0(sort(unique(y_levels)), " levels")
    )
  )


# by country

sparsity_by_dimension_c <- summary_tbl2_C %>%
  mutate(
    instrument = factor(instrument, levels = instrument_vars)
  ) %>%
  group_by(instrument, x_levels, y_levels) %>%
  summarise(
    # Sparsity
    mean_pct_empty_xy_cells = mean(mean_pct_empty_xy_cells),
    median_pct_empty_xy_cells = median(median_pct_empty_xy_cells),
    
    # Percentage of specifications in this tile that violate the inequalities
    pct_violated = 100 * mean(violated, na.rm = TRUE),
    
    # Number of specifications combined in the tile
    n_specifications = n(),
    
    # Other sparsity indicators
    mean_singleton_cells = mean(total_singleton_xy_cells),
    mean_min_table_n = mean(min_table_n),
    
    .groups = "drop"
  ) %>%
  mutate(
    x_levels = factor(
      x_levels,
      levels = sort(unique(x_levels)),
      labels = paste0(sort(unique(x_levels)), " levels")
    ),
    y_levels = factor(
      y_levels,
      levels = sort(unique(y_levels)),
      labels = paste0(sort(unique(y_levels)), " levels")
    )
  )

# Visualisation 

raw_instruments <- c(
  "rs11732044_t",
  "rs116970203_a"
)

joint_instruments <- c(
  "snp_combination",
  "snp_additive"
)


p_sparsity_raw <- sparsity_by_dimension %>%
  dplyr::filter(instrument %in% raw_instruments) %>%
  ggplot(
    aes(
      x = x_levels,
      y = y_levels,
      fill = mean_pct_empty_xy_cells
    )
  ) +
  geom_tile(colour = "white", linewidth = 0.5) +
  geom_text(
    aes(
      label = paste0(
        "E: ", sprintf("%.0f%%", mean_pct_empty_xy_cells),
        "\nV: ", sprintf("%.0f%%", pct_violated)
      )
    ),
    colour = "black",
    size = 3.0,        # ggplot text size is in mm
    
  )+
  facet_wrap(~ instrument, nrow = 1) +
  scale_fill_gradient(
    name = "Mean empty\ncells (%)",
    low = "white",
    high = "black",
    limits = c(0, 100),
    labels = scales::label_percent(scale = 1)
  ) +
  labs(
    x = "Number of exposure categories",
    y = "Number of outcome categories"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    strip.text = element_text(face = "bold")
  )

p_sparsity_raw_c <- sparsity_by_dimension_c %>%
  dplyr::filter(instrument %in% raw_instruments) %>%
  ggplot(
    aes(
      x = x_levels,
      y = y_levels,
      fill = mean_pct_empty_xy_cells
    )
  ) +
  geom_tile(colour = "white", linewidth = 0.5) +
  geom_text(
    aes(
      label = paste0(
        "E: ", sprintf("%.0f%%", mean_pct_empty_xy_cells),
        "\nV: ", sprintf("%.0f%%", pct_violated)
      )
    ),
    colour = "black",
    size = 3.0,        # ggplot text size is in mm
    
  )+
  facet_wrap(~ instrument, nrow = 1) +
  scale_fill_gradient(
    name = "Mean empty\ncells (%)",
    low = "white",
    high = "black",
    limits = c(0, 100),
    labels = scales::label_percent(scale = 1)
  ) +
  labs(
    x = "Number of exposure categories",
    y = "Number of outcome categories"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    strip.text = element_text(face = "bold")
  )



p_sparsity_joint_c <- sparsity_by_dimension_c %>%
  dplyr::filter(instrument %in% joint_instruments) %>%
  ggplot(
    aes(
      x = x_levels,
      y = y_levels,
      fill = mean_pct_empty_xy_cells
    )
  ) +
  geom_tile(colour = "white", linewidth = 0.5) +
  geom_text(
    aes(
      label = paste0(
        "E: ", sprintf("%.0f%%", mean_pct_empty_xy_cells),
        "\nV: ", sprintf("%.0f%%", pct_violated)
      )
    ),
    colour = "black",
    size = 3.0,        
  )+
  facet_wrap(~ instrument, nrow = 1) +
  scale_fill_gradient(
    name = "Mean empty\ncells (%)",
    low = "white",
    high = "black",
    limits = c(0, 100),
    labels = scales::label_percent(scale = 1)
  )+
  labs(
    x = "Number of exposure categories",
    y = "Number of outcome categories"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    strip.text = element_text(face = "bold")
  )


