# ==============================================================================
# CAUSAL-EFFECT EXISTENCE, ACE BOUNDS, AND SUPPLEMENTARY 2SLS ANALYSES
# ==============================================================================
#
# Author: Khaled Aboul Azm
#
# Script:
#   03_causal_effect_bounds_2SLS.R
#
# Purpose:
# This script evaluates evidence for the existence of a causal effect,
# calculates bounds for the average causal effect (ACE), and performs
# supplementary two-stage least-squares (2SLS) analyses.
#
# The script uses the CausalBoundsR package, which was developed specifically
# for this project and is not published on CRAN. The package source is stored
# within the project under:
#
#   packages/CausalBoundsR/
#
# The package must be installed before this script is run. If running on the genepi server, use devtools to load the package 
# devtools::load_all("../packages/CausalBoundsR")
#
# ==============================================================================
# ANALYSIS WORKFLOW
# ==============================================================================
#
# The thesis analyses are organized into the following scripts:
#
# 1. 01_descriptives_w_initial_analysis.R
#    Produces the descriptive statistics and performs the initial analyses.
#
# 2. 02_IV_inequalities.R
#    evaluates the different discretisation methods, applies the instrumental-
#    variable inequalities, and examines sparsity.
#
# 3. 03_causal_effect_bounds_2SLS.R
#    evaluates evidence for the existence of a causal effect, calculates
#    bounds for the average causal effect, and performs supplementary 2SLS
#    analyses.
#
# The cleaned analysis dataset used here was generated by the preceding data-
# management workflow and is loaded directly from:
#
#   data/vit.rda
#
# This script does not automatically source the preceding analysis scripts.
# It can be run independently provided that all required input data, packages,
# and any explicitly documented intermediate objects are available.
#
#
# ==============================================================================
# NOTES
# ==============================================================================
#
# This script was created by consolidating analyses originally contained in
# the thesis notebooks. Plots and tables are primarily generated for
# inspection during the analysis. Objects required by subsequent scripts may
# be saved explicitly where indicated.
#
# ==============================================================================



# 1. INITIAL SETUP -------------------------------------------------------------

# Remove objects left over from previous R sessions
rm(list = ls())

# Set general R options
options(
  stringsAsFactors = FALSE,
  scipen = 999,
  digits = 4
)

# Set a seed for reproducible procedures involving random processes
set.seed(12345)


# 2. REQUIRED PACKAGES ---------------------------------------------------------

# Packages included in tidyverse, such as dplyr, tidyr, ggplot2, tibble, and
# purrr, do not need to be loaded separately.
required_packages <- c(
  "tidyverse",
  "lme4",
  "lmerTest",
  "hrbrthemes",
  "ExclusionTable",
  "viridis",
  "gt",
  "AER",
  "sandwich",
  "gtsummary",
  "ggdag",
  "knitr",
  "scales"
)

devtools::load_all("../packages/CausalBoundsR")

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "The following required packages are not installed: ",
      paste(missing_packages, collapse = ", "),
      "."
    ),
    call. = FALSE
  )
}

invisible(
  lapply(
    required_packages,
    library,
    character.only = TRUE
  )
)


# 3. PROJECT DIRECTORIES -------------------------------------------------------

# The project location can be changed through the IIVITD_PROJECT_DIR
# environment variable. The GenEpi/BISON project location is used by default.
project_dir <- Sys.getenv(
  "IIVITD_PROJECT_DIR",
  unset = path.expand("~/ii2025MRVitD")
)

analysis_dir <- file.path(project_dir, "analysis")
data_dir <- file.path(project_dir, "data")
results_dir <- file.path(project_dir, "results")

tables_dir <- file.path(results_dir, "tables")
figures_dir <- file.path(results_dir, "figures")
models_dir <- file.path(results_dir, "models")


# 4. INPUT FILES ---------------------------------------------------------------

# Main cleaned analysis dataset
vit_data_file <- file.path(data_dir, "vit.rda")



# 5. DIRECTORY AND FILE CHECKS -------------------------------------------------

required_directories <- c(
  project_dir,
  analysis_dir,
  data_dir
)

missing_directories <- required_directories[
  !dir.exists(required_directories)
]

if (length(missing_directories) > 0) {
  stop(
    paste0(
      "The following required directories were not found:\n",
      paste0(" - ", missing_directories, collapse = "\n"),
      "\nCheck the project location or set IIVITD_PROJECT_DIR."
    ),
    call. = FALSE
  )
}

# Create output directories if necessary
output_directories <- c(
  results_dir,
  tables_dir,
  figures_dir,
  models_dir
)

invisible(
  lapply(
    output_directories,
    dir.create,
    recursive = TRUE,
    showWarnings = FALSE
  )
)

required_input_files <- c(
  vit_data_file,
  gwas_results
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste0(
      "The following required input files were not found:\n",
      paste0(" - ", missing_input_files, collapse = "\n"),
      "\nCheck the file locations or set the relevant environment variables."
    ),
    call. = FALSE
  )
}


# 6. LOAD ANALYSIS DATA --------------------------------------------------------

# Record the names of the objects loaded from the RData file.
loaded_vit_objects <- load(vit_data_file)

message(
  "Loaded objects from ", vit_data_file, ": ",
  paste(loaded_vit_objects, collapse = ", ")
)


# 7. SETUP SUMMARY -------------------------------------------------------------

message("Project directory: ", project_dir)
message("Analysis directory: ", analysis_dir)
message("Data directory: ", data_dir)
message("Results directory: ", results_dir)
message("GWAS results file: ", gwas_results)




###################################################################################



########################################################
# Testing for the existence of a causal effect
########################################################



# ============================================================
# 1. Define instruments
# ============================================================

instrument_vars <- c(
  "rs11732044_t",
  "rs116970203_a",
  "snp_combination",
  "snp_additive"
)


# ============================================================
# 2. Make vitamin D decile numeric
# ============================================================
#
# This assumes vitd_decile is coded as:
# 1 = lowest vitamin D decile
# ...
# 10 = highest vitamin D decile
#
# The IV model estimates the effect per 1-decile increase.
# We later multiply by 9 to obtain the decile 1 -> 10 contrast.
# ============================================================

vit_disc_thesis$vitd_decile_num <- as.numeric(
  as.character(vit_disc_thesis$vitd_decile)
)


# Check that the coding is correct
table(vit_disc_thesis$vitd_decile_num, useNA = "ifany")


# ============================================================
# 3. Define covariates
# ============================================================

covariates <- paste(
  paste0("pc", 1:10),
  collapse = " + "
)


# ============================================================
# 4. Fit IV models
# ============================================================

# Lists to store the RAW models
iv_unadj_models <- list()
iv_adj_models <- list()


for (inst in instrument_vars) {
  
  # ----------------------------------------------------------
  # Unadjusted model
  # ----------------------------------------------------------
  
  unadj_formula <- as.formula(
    paste(
      "zmets_binary_median ~ vitd_decile_num |",
      inst
    )
  )
  
  iv_unadj_models[[inst]] <- ivreg(
    unadj_formula,
    data = vit_disc_thesis
  )
  
  
  # ----------------------------------------------------------
  # Adjusted model
  # ----------------------------------------------------------
  
  adj_formula <- as.formula(
    paste(
      "zmets_binary_median ~ vitd_decile_num +",
      covariates,
      "|",
      inst,
      "+",
      covariates
    )
  )
  
  iv_adj_models[[inst]] <- ivreg(
    adj_formula,
    data = vit_disc_thesis
  )
}


# ============================================================
# 5. Function to extract IV estimates
# ============================================================
#
# The raw IV coefficient is the effect of a ONE-DECILE
# increase in vitamin D.
#
# To obtain the effect of going from decile 1 -> decile 10:
#
#       10 - 1 = 9 decile increments
#
# Therefore:
#
#       estimate_1_to_10 = estimate_per_decile * 9
#       SE_1_to_10       = SE_per_decile * 9
#
# Because the outcome is binary, the estimates are on the
# probability/risk-difference scale.
# ============================================================

extract_iv_coefs <- function(object_list, model_type) {
  
  purrr::map_dfr(names(object_list), function(inst) {
    
    model <- object_list[[inst]]
    
    # Get coefficient matrix
    coef_mat <- summary(model)$coefficients
    
    # Check that the exposure is present
    if (!"vitd_decile_num" %in% rownames(coef_mat)) {
      return(NULL)
    }
    
    # --------------------------------------------------------
    # Per-decile IV estimate
    # --------------------------------------------------------
    
    est_per_decile <- coef_mat[
      "vitd_decile_num",
      "Estimate"
    ]
    
    se_per_decile <- coef_mat[
      "vitd_decile_num",
      "Std. Error"
    ]
    
    
    # --------------------------------------------------------
    # Convert to decile 1 -> decile 10 contrast
    # --------------------------------------------------------
    
    n_decile_steps <- 10 - 1
    
    est_1_to_10 <- est_per_decile * n_decile_steps
    
    se_1_to_10 <- se_per_decile * n_decile_steps
    
    
    # --------------------------------------------------------
    # 95% CI
    # --------------------------------------------------------
    
    lower_1_to_10 <- est_1_to_10 - 1.96 * se_1_to_10
    
    upper_1_to_10 <- est_1_to_10 + 1.96 * se_1_to_10
    
    
    # --------------------------------------------------------
    # Return results
    # --------------------------------------------------------
    
    tibble(
      instrument = inst,
      model = model_type,
      
      # Original IV estimate
      estimate_per_decile = est_per_decile,
      std_error_per_decile = se_per_decile,
      
      # Main estimand:
      # vitamin D decile 1 -> decile 10
      estimate_1_to_10 = est_1_to_10,
      std_error_1_to_10 = se_1_to_10,
      
      lower_1_to_10 = lower_1_to_10,
      upper_1_to_10 = upper_1_to_10
    )
  })
}


# ============================================================
# 6. Combine unadjusted + adjusted results
# ============================================================

coef_df <- dplyr::bind_rows(
  
  extract_iv_coefs(
    iv_unadj_models,
    "Unadjusted"
  ),
  
  extract_iv_coefs(
    iv_adj_models,
    "Adjusted"
  )
)


# ============================================================
# 7. View results
# ============================================================

print(coef_df)


# ============================================================
# 8. Optional: create a cleaner reporting table
# ============================================================

iv_results <- coef_df %>%
  mutate(
    
    # Express probability difference as percentage points
    estimate_percentage_points = estimate_1_to_10 * 100,
    
    lower_percentage_points = lower_1_to_10 * 100,
    
    upper_percentage_points = upper_1_to_10 * 100,
    
    # Formatted estimate + CI
    estimate_ci = sprintf(
      "%.3f (%.3f, %.3f)",
      estimate_1_to_10,
      lower_1_to_10,
      upper_1_to_10
    ),
    
    # Formatted percentage-point version
    estimate_ci_percentage_points = sprintf(
      "%.1f (%.1f, %.1f)",
      estimate_percentage_points,
      lower_percentage_points,
      upper_percentage_points
    )
  ) %>%
  select(
    instrument,
    model,
    estimate_1_to_10,
    std_error_1_to_10,
    lower_1_to_10,
    upper_1_to_10,
    estimate_ci,
    estimate_ci_percentage_points
  )


print(iv_results)


# ============================================================
# 3. Forest Plot
#    IV-estimated change from vitamin D decile 0 -> 9
# ============================================================

ggplot(
  coef_df %>%
    mutate(
      instrument_label = case_when(
        instrument == "rs11732044_t" ~ "SNP 1",
        instrument == "rs116970203_a" ~ "SNP 2",
        instrument == "snp_combination" ~ "Joint instrument",
        instrument == "snp_additive" ~ "Joint instrument",
        TRUE ~ instrument
      )
    ),
  aes(
    x = estimate_1_to_10,
    y = instrument_label,
    color = model
  )
) +
  geom_vline(
    xintercept = 0,
    linetype = "dashed",
    color = "black",
    linewidth = 0.8
  ) +
  geom_pointrange(
    aes(
      xmin = lower_1_to_10,
      xmax = upper_1_to_10
    ),
    position = position_dodge(width = 0.5),
    size = 0.8
  ) +
  scale_color_manual(
    values = c(
      "Unadjusted" = "#999999",
      "Adjusted" = "#d7191c"
    )
  ) +
  theme_minimal(base_size = 14) +
  labs(
    title = "IV Estimates of Vitamin D on Metabolic Syndrome",
    subtitle = "Risk difference for vitamin D decile 0 vs decile 9",
    x = "Risk Difference (95% CI)",
    y = "Genetic Instrument",
    color = "Model"
  ) +
  theme(
    legend.position = "bottom"
  )

# ============================================================
# Visualisations
# ============================================================

ggplot(
  vit_disc_thesis,
  aes(
    x = factor(snp_additive),
    y = vitd25_nmol
  )
) +
  geom_violin(
    aes(fill = factor(snp_additive)),
    alpha = 0.4,
    color = NA
  ) +
  geom_boxplot(
    width = 0.2,
    color = "black",
    outlier.shape = NA,
    alpha = 0.6
  ) +
  geom_jitter(
    width = 0.15,
    alpha = 0.1,
    size = 1,
    color = "gray30"
  ) +
  scale_fill_brewer(
    palette = "Blues"
  ) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Vitamin D Levels by Genetic Score",
    x = "Additive SNP Score (Number of Risk Alleles)",
    y = "Circulating Vitamin D (nmol/L)",
    fill = "Allele Count"
  ) +
  theme(
    legend.position = "none"
  )

# 1. Function to extract F-statistics from raw ivreg models
extract_f_stats <- function(model_list, model_type) {
  purrr::map_dfr(names(model_list), function(inst) {
    
    # Explicitly call summary() with diagnostics = TRUE on the raw model
    diag_mat <- summary(model_list[[inst]], diagnostics = TRUE)$diagnostics
    
    # Check if diagnostics exist and extract the Weak instruments statistic
    if (!is.null(diag_mat) && "Weak instruments" %in% rownames(diag_mat)) {
      tibble::tibble(
        instrument = inst,
        model = model_type,
        f_statistic = diag_mat["Weak instruments", "statistic"]
      )
    }
  })
}

# 2. Combine unadjusted and adjusted F-statistics using the correct list names
f_stat_df <- dplyr::bind_rows(
  extract_f_stats(iv_unadj_models, "Unadjusted"),
  extract_f_stats(iv_adj_models, "Adjusted")
)

# 3. Plot the F-statistics
ggplot(f_stat_df, aes(x = instrument, y = f_statistic, fill = model)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7, color = "black") +
  # Add the critical threshold line
  geom_hline(yintercept = 10, linetype = "dashed", color = "red", linewidth = 1) +
  annotate("text", x = 1, y = 15, label = "Threshold (F = 10)", color = "red", hjust = 0) +
  scale_fill_manual(values = c("Unadjusted" = "#999999", "Adjusted" = "#2c7bb6")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Instrument Strength: First-Stage F-Statistics",
    subtitle = "Red dashed line indicates the conventional threshold for weak instruments",
    x = "Genetic Instrument",
    y = "F-Statistic",
    fill = "Model Fit"
  ) +
  theme(legend.position = "top")

ggplot(vit_disc_thesis, aes(x = factor(snp_additive), y = z_mets)) +
  # Add the violin for distribution shape
  geom_violin(aes(fill = factor(snp_additive)), alpha = 0.4, color = NA) +
  # Add the boxplot for medians and quartiles
  geom_boxplot(width = 0.2, color = "black", outlier.shape = NA, alpha = 0.6) +
  # Add jittered points to show actual sample size and spread
  geom_jitter(width = 0.15, alpha = 0.1, size = 1, color = "gray30") +
  # Using OrRd (Orange-Red) to differentiate the outcome from the exposure plot
  scale_fill_brewer(palette = "OrRd") +
  theme_minimal(base_size = 14) +
  labs(
    title = "Metabolic Syndrome by Genetic Score",
    x = "Additive SNP Score (Number of risk alleles)",
    y = "Metabolic Syndrome Score (z_mets)",
    fill = "Allele Count"
  ) +
  theme(legend.position = "none")

# Tables

iv_table <- coef_df %>%
  mutate(
    
    Instrument = case_when(
      instrument == "rs11732044_t"    ~ "rs11732044",
      instrument == "rs116970203_a"   ~ "rs116970203",
      instrument == "snp_combination" ~ "SNP combination",
      instrument == "snp_additive"    ~ "SNP additive score",
      TRUE ~ instrument
    ),
    
    Estimate = sprintf(
      "%.3f",
      estimate_1_to_10
    ),
    
    `95% CI` = sprintf(
      "%.3f, %.3f",
      lower_1_to_10,
      upper_1_to_10
    )
  ) %>%
  select(
    model,
    Instrument,
    Estimate,
    `95% CI`
  )


# ------------------------------------------------------------
# 2. Split into unadjusted and adjusted
# ------------------------------------------------------------

iv_unadjusted <- iv_table %>%
  filter(model == "Unadjusted") %>%
  select(
    Instrument,
    Estimate,
    `95% CI`
  )

iv_adjusted <- iv_table %>%
  filter(model == "Adjusted") %>%
  select(
    Instrument,
    Estimate,
    `95% CI`
  )


# ------------------------------------------------------------
# 3. Add section headers
# ------------------------------------------------------------

unadjusted_section <- tibble(
  Instrument = "Unadjusted IV estimates",
  Estimate = "",
  `95% CI` = ""
)

adjusted_section <- tibble(
  Instrument = "Adjusted IV estimates",
  Estimate = "",
  `95% CI` = ""
)


# ------------------------------------------------------------
# 4. Combine
# ------------------------------------------------------------

iv_table_final <- bind_rows(
  unadjusted_section,
  iv_unadjusted,
  adjusted_section,
  iv_adjusted
)


# ------------------------------------------------------------
# 5. Rename columns for final table
# ------------------------------------------------------------

colnames(iv_table_final) <- c(
  "Instrument",
  "Risk difference (decile 0--9)",
  "95\\% CI"
)


# Check
print(iv_table_final)



###############################################
# Bounding the Average Causal Effect
# slack_val = 0
# tolerance = 0.0000000000000000000000000000000000000000000000001
###############################################

outcome_var   <- "zmets_binary_median"
treatment_var <- "vitd_decile"

instruments <- c(
  "rs11732044_t",
  "rs116970203_a",
  "snp_combination",
  "snp_additive"
)

# 3. Loop over each instrument
for (inst in instruments) {
  message("\n--- Processing Instrument: ", inst, " ---")
  
  # Compute the causal bounds
  results <- compute_ace_bounds(
    data = vit_disc_thesis, 
    outcome = outcome_var, 
    treatment = treatment_var, 
    instrument = inst,
    slack_val = 0,
    tolerance = 0.0000000000000000000000000000000000000000000000001,
    verbose = FALSE)
  
  print(results)
  # Clean up instrument name for filenames (e.g., rs11732044_t -> rs11732044)
  clean_inst <- gsub("_t$|_a$", "", inst)
  
  # Define consistent filenames
  file_base <- paste0("ace_bounds2_", clean_inst)
  rds_path  <- file.path(data_dir, paste0(file_base, ".rds"))
  tex_path  <- file.path(base_dir, paste0(file_base, ".tex"))
  
  # Save the raw R object (RDS) for future analysis inside the datasets subfolder
  saveRDS(results, file = rds_path)
  message("Saved RDS dataset to: ", rds_path)
  
  # Convert results to a clean data frame for LaTeX export
  tbl_data <- if (is.data.frame(results)) {
    results
  } else if (is.list(results) && "bounds" %in% names(results)) {
    # Fallback if compute_ace_bounds returns a list with a specific bounds element
    results$bounds
  } else {
    as.data.frame(results)
  }
  
  # Generate a publication-ready LaTeX table using gt
  latex_table <- tbl_data %>%
    gt() %>%
    tab_header(
      title = "Average Causal Effect (ACE) Bounds",
      subtitle = paste0("Instrument: ", inst, " | Treatment: ", treatment_var, " | Outcome: ", outcome_var)
    ) %>%
    # Format all decimal numbers to 4 decimal places for scientific precision
    fmt_number(
      columns = where(is.numeric),
      decimals = 4
    ) %>%
    tab_options(
      table.width = pct(100),
      column_labels.font.weight = "bold"
    )
  
  # Export to LaTeX (automatically wraps in a longtable environment if the table is long)
  #gtsave(latex_table, filename = tex_path)
  message("Saved LaTeX table to: ", tex_path)
}

message("\nPipeline complete! All datasets and tables saved successfully.")


# ==============================================
# Country Adjussted bounds
# ==============================================


country_weights <- vit_disc_thesis %>%
  count(country) %>%
  mutate(weight = n / sum(n))

# 3. Loop over each instrument
for (inst in instruments) {
  message("\n--- Processing Instrument: ", inst, " ---")
  
  # --- NEW: Stratify by country and compute bounds ---
  strata_results_list <- lapply(1:nrow(country_weights), function(i) {
    c_name <- country_weights$country[i]
    c_weight <- country_weights$weight[i]
    
    # Subset data for the specific country
    subset_data <- vit_disc_thesis %>% filter(country == c_name)
    
    # Compute bounds for this country
    res <- compute_ace_bounds(
      data = subset_data, 
      outcome = outcome_var, 
      treatment = treatment_var, 
      instrument = inst,
      slack_val = 0,
      tolerance = 0.0000000000000000000000000000000000000000000000001,
      verbose = FALSE
    )
    
    print(res)
    
    # Standardize to data frame
    res_df <- if (is.data.frame(res)) { res } else if (is.list(res) && "bounds" %in% names(res)) { res$bounds } else { as.data.frame(res) }
    
    # Tag with country and weight
    res_df$country <- c_name
    res_df$weight <- c_weight
    
    return(res_df)
  })
  
  # Combine all country-specific bounds into one dataframe
  all_strata_df <- bind_rows(strata_results_list)
  
  # --- NEW: Calculate the weighted average to get the adjusted bounds ---
  # Identify numeric columns (bounds/estimates) and grouping columns (e.g., treatment levels, if your output has multiple rows)
  numeric_cols <- names(all_strata_df)[sapply(all_strata_df, is.numeric) & !names(all_strata_df) %in% c("weight")]
  group_cols <- names(all_strata_df)[!sapply(all_strata_df, is.numeric) & !names(all_strata_df) %in% c("country")]
  
  if (length(group_cols) > 0) {
    tbl_data <- all_strata_df %>%
      group_by(across(all_of(group_cols))) %>%
      summarize(across(all_of(numeric_cols), ~ sum(.x * weight)), .groups = "drop")
  } else {
    tbl_data <- all_strata_df %>%
      summarize(across(all_of(numeric_cols), ~ sum(.x * weight)))
  }
  
  # Clean up instrument name for filenames (e.g., rs11732044_t -> rs11732044)
  clean_inst <- gsub("_t$|_a$", "", inst)
  
  # Define consistent filenames
  file_base <- paste0("ace_bounds_adjusted_", clean_inst)
  rds_path  <- file.path(data_dir, paste0(file_base, ".rds"))
  tex_path  <- file.path(base_dir, paste0(file_base, ".tex"))
  
  # Save the raw adjusted R object (RDS)
  saveRDS(tbl_data, file = rds_path)
  message("Saved adjusted RDS dataset to: ", rds_path)
  
  # Generate a publication-ready LaTeX table using gt
  latex_table <- tbl_data %>%
    gt() %>%
    tab_header(
      title = "Country-Adjusted ACE Bounds",
      subtitle = paste0("Instrument: ", inst, " | Treatment: ", treatment_var, " | Outcome: ", outcome_var)
    ) %>%
    fmt_number(
      columns = where(is.numeric),
      decimals = 4
    ) %>%
    tab_options(
      table.width = pct(100),
      column_labels.font.weight = "bold"
    )
  
  # Export to LaTeX
  #gtsave(latex_table, filename = tex_path)
  message("Saved LaTeX table to: ", tex_path)
}

message("\nPipeline complete! All country-adjusted datasets and tables saved successfully.")


# Visualisation 


instruments <- c(
  "rs11732044_t",
  "rs116970203_a",
  "snp_combination",
  "snp_additive"
)

# Retain ONLY unadjusted 2SLS estimates
iv_plot <- coef_df %>%
  dplyr::filter(model == "Unadjusted") %>%  # Confirm name with unique(coef_df$model)
  dplyr::transmute(
    instrument,
    method = "2SLS estimate (95% CI)",
    estimate = estimate_1_to_10,
    lower = lower_1_to_10,
    upper = upper_1_to_10
  )

# ACE bounds
ace_plot <- purrr::map_dfr(instruments, function(inst) {
  
  clean_inst <- gsub("_t$|_a$", "", inst)
  
  ace_result <- readRDS(
    file.path(data_dir, paste0("ace_bounds_", clean_inst, ".rds"))
  )
  
  if (is.list(ace_result) && "bounds" %in% names(ace_result)) {
    ace_result <- ace_result$bounds
  }
  
  ace_result <- as.data.frame(ace_result)
  
  ace_result %>%
    dplyr::transmute(
      instrument = inst,
      method = "ACE bounds",
      estimate = NA_real_,
      lower = lower,
      upper = upper
    )
})

# Sanity checks: should be one row for each instrument
iv_plot %>% dplyr::count(instrument)
ace_plot %>% dplyr::count(instrument)

plot_df <- dplyr::bind_rows(ace_plot, iv_plot) %>%
  dplyr::mutate(
    instrument_label = dplyr::recode(
      instrument,
      "rs11732044_t"     = "rs11732044",
      "rs116970203_a"    = "rs116970203",
      "snp_combination"  = "Combined SNP score",
      "snp_additive"     = "Additive SNP score",
      .default = instrument
    ),
    
    row_label = paste(instrument_label, method, sep = " — "),
    
    # Text to display beside each interval
    annotation = dplyr::if_else(
      method == "ACE bounds",
      sprintf("[%.2f, %.2f]", lower, upper),
      sprintf("%.2f [%.2f, %.2f]", estimate, lower, upper)
    ),
    
    row_label = factor(row_label, levels = rev(unique(row_label)))
  )

p <- ggplot(plot_df, aes(y = row_label)) +
  
  geom_vline(
    xintercept = 0,
    linetype = "dashed",
    colour = "grey40"
  ) +
  
  geom_segment(
    aes(
      x = lower,
      xend = upper,
      yend = row_label,
      colour = method
    ),
    linewidth = 1
  ) +
  
  geom_point(
    data = dplyr::filter(
      plot_df,
      method == "2SLS estimate (95% CI)"
    ),
    aes(x = estimate, colour = method),
    size = 2.8
  ) +
  
  # Small numerical labels to the right of the intervals
  geom_text(
    aes(
      x = upper,
      label = annotation,
      colour = method
    ),
    hjust = -0.08,
    size = 2.2,
    show.legend = FALSE
  ) +
  
  scale_colour_manual(
    values = c(
      "ACE bounds" = "#1b9e77",
      "2SLS estimate (95% CI)" = "#d95f02"
    )
  ) +
  
  # Adds room to the right for the annotation labels
  scale_x_continuous(
    expand = expansion(mult = c(0.03, 0.32))
  ) +
  
  # Allows text outside the plotting panel
  coord_cartesian(clip = "off") +
  
  labs(
    x = "Causal risk difference: highest versus lowest vitamin D decile",
    y = NULL,
    colour = NULL,
    title = "ACE bounds and unadjusted 2SLS estimates",
    subtitle = paste(
      "Green lines: ACE bounds; orange point/line: unadjusted 2SLS estimate and 95% confidence interval"
    )
  ) +
  
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.major.y = element_blank(),
    plot.margin = margin(5.5, 130, 5.5, 5.5)
  )

print(p)


# Keep unadjusted 2SLS estimates only
iv_unadjusted <- coef_df %>%
  dplyr::filter(model == "Unadjusted") %>%  # change if exact name differs
  dplyr::transmute(
    instrument,
    estimate_2sls = estimate_1_to_10
  )

# Join one 2SLS estimate to one ACE bound interval per instrument
comparison_df <- ace_plot %>%
  dplyr::select(
    instrument,
    ace_lower = lower,
    ace_upper = upper
  ) %>%
  dplyr::left_join(iv_unadjusted, by = "instrument") %>%
  dplyr::mutate(
    instrument_label = dplyr::recode(
      instrument,
      "rs11732044_t"     = "rs11732044 (GC)",
      "rs116970203_a"    = "rs116970203 (PDE3B)",
      "snp_combination"  = "Combined (Joint)",
      "snp_additive"     = "Combined (Additive)",
      .default = instrument
    ),
    
    # Arrange labels in desired top-to-bottom order
    instrument_label = factor(
      instrument_label,
      levels = rev(c(
        "rs11732044 (GC)",
        "rs116970203 (PDE3B)",
        "Combined (Additive)",
        "Combined (Joint)"
      ))
    ),
    
    label_lower = sprintf("%.3f", ace_lower),
    label_upper = sprintf("%.3f", ace_upper),
    label_2sls  = sprintf("%.3f", estimate_2sls)
  )
p_comparison <- ggplot(
  comparison_df,
  aes(y = instrument_label)
) +
  
  # Null line
  geom_vline(
    xintercept = 0,
    linetype = "dashed",
    colour = "grey65",
    linewidth = 0.5
  ) +
  
  # ACE bound interval
  geom_segment(
    aes(
      x = ace_lower,
      xend = ace_upper,
      yend = instrument_label
    ),
    colour = "#2F3548",
    linewidth = 0.8
  ) +
  
  # Endpoint markers for ACE bounds
  geom_point(
    aes(x = ace_lower),
    colour = "#2F3548",
    size = 2.6
  ) +
  
  geom_point(
    aes(x = ace_upper),
    colour = "#2F3548",
    size = 2.6
  ) +
  
  # Unadjusted 2SLS estimate
  geom_point(
    aes(x = estimate_2sls),
    colour = "#E41A1C",
    size = 3.5
  ) +
  
  # Lower ACE-bound label
  geom_text(
    aes(
      x = ace_lower,
      label = label_lower
    ),
    vjust = -1.0,
    hjust = 0.5,
    size = 2.5,
    colour = "#555555"
  ) +
  
  # Upper ACE-bound label
  geom_text(
    aes(
      x = ace_upper,
      label = label_upper
    ),
    vjust = -1.0,
    hjust = 0.5,
    size = 2.5,
    colour = "#555555"
  ) +
  
  # 2SLS estimate label
  geom_text(
    aes(
      x = estimate_2sls,
      label = label_2sls
    ),
    vjust = -1.2,
    hjust = 0.5,
    size = 2.6,
    fontface = "bold",
    colour = "#E41A1C"
  ) +
  
  scale_x_continuous(
    breaks = seq(-1, 1, by = 0.25),
    limits = c(-1, 1)
  ) +
  
  labs(
    title = "Non-parametric ACE bounds and the unadjusted 2SLS estimates",
    x = "ACE / Risk difference: vitamin D decile 9 versus decile 0",
    y = NULL
  ) +
  
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(face = "bold", colour = "#2F3548"),
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(size = 10),
    plot.margin = margin(10, 15, 10, 15)
  )

print(p_comparison)


ggsave(
  file.path(base_dir, "2sls_points_with_ace_bounds2.pdf"),
  p_comparison,
  width = fig_width,
  height = fig_height
)
